### ISSUE TITLE
프로젝트 구조 분석하기

### ISSUE THREAD

**Issue by ToySin** [DongDongYoung/prompt-share-backend#1]
@skditjsdud35 가 주요 화면 캡쳐해서 올려주면

- [x] 주요 엔티티 설계해서 ERD로 추가하기
    - [x] 프롬프트

**Comment by skditjsdud35** [comment]
1. 메인 화면 (로그인 x)


![Image](https://user-images.githubusercontent.com/68502219/230699029-dd733d95-ec7a-4162-a236-0e53968373d8.png)

**Comment by skditjsdud35** [comment]
2. 메인 화면 (로그인 O)



![Image](https://user-images.githubusercontent.com/68502219/230699071-a759c158-a49e-4e7b-9301-3d1cb20e5310.png)

**Comment by skditjsdud35** [comment]
3. 프롬프트 작성 화면



![Image](https://user-images.githubusercontent.com/68502219/230699100-c48c8d0a-93d0-49dd-bb05-09696f084706.png)

**Comment by skditjsdud35** [comment]
4. 프롬프트 상세 화면
**(밑에 잘렸는데 수정, 삭제 버튼도 있어요. 본인이 작성한 글인 경우 프롬프트 상세화면에서 수정/삭제 가능)**



![Image](https://user-images.githubusercontent.com/68502219/230699127-6a3971dd-5328-4433-a3f9-132ae9bc2fbe.png)

**Comment by skditjsdud35** [comment]
5. 마이페이지 화면 (로그인 시)



![Image](https://user-images.githubusercontent.com/68502219/230699147-061d78e6-f6a1-45c9-be09-fda9d9d1e7d9.png)

**Comment by skditjsdud35** [comment]
6. 로그인, 회원가입 모달



![Image](https://user-images.githubusercontent.com/68502219/230699171-66a7e31e-0896-4eae-8115-0eaae66b2d5a.png)



![Image](https://user-images.githubusercontent.com/68502219/230699172-ecae6e24-f152-46cc-a6a7-1126a919d8df.png)

**Comment by ToySin** [comment]
프롬프트 ERD 완성
- 기본적인 CRUD를 위한 기본 기능으로만 구성
- 회원 로직 구현 후 수정할 예정
- 좋아요와 조회수는 나중에 따로 구현 예정

https://github.com/DongDongYoung/prompt-share-backend/blob/feature/%231-project-structure/document/prompt-share-erd.svg
