### ISSUE TITLE
프롬프트 API

### ISSUE THREAD

**Issue by ToySin** [DongDongYoung/prompt-share-backend#4]
- [x] 프롬프트 API 설계
- [ ] 프롬프트 API 테스트 정의
- [ ] 프롬프트 API 구현

**Comment by ToySin** [comment]
기본적인 API 설계 해봤어~!

https://docs.google.com/spreadsheets/d/e/2PACX-1vRcvD_GKZDAqt5ceVtgb1E5cH2Muwf4aiCOVCxbsfSpbZL8z_3GvKZnVPUZaQnypCrgoUhA-bw3gmwD/pub?output=pdf

수정할거 댓글 달아줘잉

**Comment by ToySin** [comment]
하나의 게시글 역할 하는걸 prompt 라고 이름 붙였어
처음에 dialog라고 했다가 프롬프트가 어감이 더 좋은것 같아서 그렇게 정했구
동의하면 ERD도 그냥 prompt 라고 수정할게
ERD: PromptDialog -> Prompt

**Comment by skditjsdud35** [comment]
확인했습니다👍
